import { Layout } from '../lib/types';

export const mockGenerateCode = async (layout: Layout): Promise<{ jsx: string; readme: string }> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      const componentsJsx = layout.components.map(comp => {
        if (comp.type === 'text') return `<h1 className="text-4xl font-bold mb-4">${comp.props.text}</h1>`;
        if (comp.type === 'button') return `<button className="px-6 py-2 bg-purple-600 rounded hover:bg-purple-700 transition">${comp.props.text}</button>`;
        if (comp.type === 'image') return `<img src="${comp.props.src}" alt="Generated" className="rounded-lg shadow-lg mb-6" />`;
        if (comp.type === 'card') return `<div className="p-6 bg-gray-900 rounded-xl border border-gray-800">${comp.props.children ? '...' : 'Card Content'}</div>`;
        return '';
      }).join('\n      ');

      const fullJsx = `import React from 'react';

export default function GeneratedPage() {
  return (
    <div className="min-h-screen bg-black text-white p-8">
      ${componentsJsx}
    </div>
  );
}`;

      resolve({
        jsx: fullJsx,
        readme: `# Generated Project\n\nThis project was generated by Neural UI AI.\n\n## Setup\n1. npm install\n2. npm run dev`
      });
    }, 2000);
  });
};

export const mockOptimizeCode = async (jsx: string): Promise<{ optimizedJsx: string; notes: string }> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        optimizedJsx: jsx.replace('className="', 'className="hover:scale-105 transition-transform duration-300 '),
        notes: '- Added hover effects for better interactivity.\n- Improved accessibility attributes.\n- Optimized tailwind classes.'
      });
    }, 2000);
  });
};
