import { Layout } from '../lib/types';

export interface GeneratedFile {
  name: string;
  content: string;
  language: string;
}

export interface GenerationResult {
  files: GeneratedFile[];
  readme: string;
  notes?: string;
}

export const mockGenerateCode = async (layout: Layout): Promise<GenerationResult> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      // Mock recursive generation
      const generateComponentJsx = (components: any[]): string => {
         return components.map(comp => {
            let content = '';
            const props = comp.props;
            
            if (comp.type === 'text') content = `<h1 className="text-4xl font-bold mb-4 ${props.color}">${props.text}</h1>`;
            else if (comp.type === 'button') content = `<button className="px-6 py-2 bg-primary text-black rounded hover:opacity-90 transition shadow-lg shadow-primary/20">${props.text}</button>`;
            else if (comp.type === 'image') content = `<img src="${props.src}" alt="Generated" className="rounded-lg shadow-lg mb-6 w-full" />`;
            else if (comp.type === 'container' || comp.type === 'card') {
               const childrenJsx = comp.children ? generateComponentJsx(comp.children) : '';
               content = `<div className="${props.padding} ${props.backgroundColor} ${props.borderRadius} border border-white/10 relative overflow-hidden">
                 ${childrenJsx}
               </div>`;
            }
            return content;
         }).join('\n      ');
      };

      const fullJsx = `import React from 'react';

export default function GeneratedPage() {
  return (
    <div className="min-h-screen bg-black text-white p-8 font-sans">
      <div className="max-w-5xl mx-auto space-y-8">
        ${generateComponentJsx(layout.components)}
      </div>
    </div>
  );
}`;

      const css = `@import "tailwindcss";

:root {
  --primary: #FFD700;
  --background: #000000;
}

body {
  background-color: var(--background);
  color: white;
}`;

      resolve({
        files: [
          { name: 'App.jsx', content: fullJsx, language: 'jsx' },
          { name: 'index.css', content: css, language: 'css' },
          { name: 'components/Button.jsx', content: 'export const Button = () => <button>Click</button>;', language: 'jsx' }
        ],
        readme: `# Generated Project\n\nThis project was generated by Neural UI AI.\n\n## Setup\n1. npm install\n2. npm run dev`,
        notes: "Generated multi-file project structure based on your current layout."
      });
    }, 2000);
  });
};

export const mockOptimizeCode = async (jsx: string): Promise<{ optimizedJsx: string; notes: string }> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        optimizedJsx: jsx.replace('className="', 'className="hover:scale-105 transition-transform duration-300 '),
        notes: '- Added hover effects for better interactivity.\n- Improved accessibility attributes.\n- Optimized tailwind classes.'
      });
    }, 2000);
  });
};
