import React, { useState } from 'react';
import { useProject } from '../context/ProjectContext';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { 
  Save, 
  Wand2, 
  Sparkles, 
  Play, 
  Code,
  Loader2,
  Share2
} from 'lucide-react';
import { mockGenerateCode, mockOptimizeCode } from '../services/mockAi';
import { useToast } from '@/hooks/use-toast';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';

export function Topbar({ onPreview }: { onPreview: () => void }) {
  const { saveProject, layout } = useProject();
  const { toast } = useToast();
  const [isGenerating, setIsGenerating] = useState(false);
  const [isOptimizing, setIsOptimizing] = useState(false);
  const [generatedResult, setGeneratedResult] = useState<{jsx: string, readme: string, notes?: string} | null>(null);
  const [showResultDialog, setShowResultDialog] = useState(false);

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      const result = await mockGenerateCode(layout);
      setGeneratedResult(result);
      setShowResultDialog(true);
      toast({
        title: "Code Generated",
        description: "Your layout has been converted to React code.",
      });
    } catch (error) {
      toast({
        title: "Error",
        description: "Failed to generate code.",
        variant: "destructive"
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleOptimize = async () => {
    setIsOptimizing(true);
    try {
      const result = await mockOptimizeCode("<div>Placeholder for current layout JSX</div>");
      setGeneratedResult({ jsx: result.optimizedJsx, readme: "Optimized Output", notes: result.notes });
      setShowResultDialog(true);
      toast({
        title: "Optimization Complete",
        description: "AI has improved your code structure.",
      });
    } catch (error) {
      toast({
         title: "Error",
         description: "Failed to optimize code.",
         variant: "destructive"
       });
    } finally {
      setIsOptimizing(false);
    }
  };

  return (
    <>
      <header className="h-16 border-b border-border bg-background/80 backdrop-blur-md flex items-center justify-between px-6 sticky top-0 z-50">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-primary rounded-lg flex items-center justify-center text-primary-foreground font-bold font-mono">
            N
          </div>
          <span className="font-bold text-lg tracking-tight">Neural UI</span>
        </div>

        <div className="flex items-center gap-2">
          <Button 
            variant="ghost" 
            size="sm" 
            onClick={saveProject}
            className="text-muted-foreground hover:text-foreground"
          >
            <Save className="w-4 h-4 mr-2" />
            Save
          </Button>

          <Button
            variant="ghost"
            size="sm"
            onClick={onPreview}
            className="text-muted-foreground hover:text-foreground"
          >
            <Play className="w-4 h-4 mr-2" />
            Preview
          </Button>

          <div className="h-6 w-px bg-border mx-2" />

          <Button 
            variant="outline" 
            size="sm" 
            onClick={handleGenerate}
            disabled={isGenerating}
            className="border-primary/20 hover:border-primary/50 text-primary hover:bg-primary/5"
          >
            {isGenerating ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Code className="w-4 h-4 mr-2" />}
            Generate Code
          </Button>

          <Button 
            size="sm" 
            onClick={handleOptimize}
            disabled={isOptimizing}
            className="bg-primary hover:bg-primary/90 text-white shadow-lg shadow-primary/20"
          >
            {isOptimizing ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Sparkles className="w-4 h-4 mr-2" />}
            Optimize (AI)
          </Button>
        </div>
      </header>

      <Dialog open={showResultDialog} onOpenChange={setShowResultDialog}>
        <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto bg-card border-border">
          <DialogHeader>
            <DialogTitle>AI Output</DialogTitle>
            <DialogDescription>
              Here is the code generated by Neural UI.
            </DialogDescription>
          </DialogHeader>
          
          {generatedResult && (
            <div className="space-y-4 mt-4">
              {generatedResult.notes && (
                <div className="bg-primary/10 border border-primary/20 p-4 rounded-lg">
                  <h3 className="font-bold text-primary mb-2 flex items-center gap-2">
                    <Sparkles size={16} /> Optimization Notes
                  </h3>
                  <pre className="whitespace-pre-wrap text-sm">{generatedResult.notes}</pre>
                </div>
              )}
              
              <div className="space-y-2">
                <Label>React JSX</Label>
                <div className="relative">
                   <pre className="p-4 rounded-lg bg-black/50 border border-white/10 overflow-x-auto text-xs font-mono text-gray-300">
                     {generatedResult.jsx}
                   </pre>
                </div>
              </div>

              <div className="space-y-2">
                <Label>README.md</Label>
                 <pre className="p-4 rounded-lg bg-black/50 border border-white/10 overflow-x-auto text-xs font-mono text-gray-300">
                   {generatedResult.readme}
                 </pre>
              </div>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </>
  );
}
